"""change msg

Revision ID: 4886ed252193
Revises: a5965afb3323
Create Date: 2024-12-17 20:06:49.583923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4886ed252193'
down_revision = 'a5965afb3323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acceleration_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unix_timestamp', sa.BigInteger(), nullable=False))
        batch_op.drop_index('ix_acceleration_user_id_time')
        batch_op.create_index('ix_acceleration_user_id_time', ['user_id', 'unix_timestamp'], unique=False)
        batch_op.drop_column('unix_timestamp_in_ms')

    with op.batch_alter_table('heartrate_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unix_timestamp', sa.BigInteger(), nullable=False))
        batch_op.drop_index('ix_heartrate_user_id_time')
        batch_op.create_index('ix_heartrate_user_id_time', ['user_id', 'unix_timestamp'], unique=False)
        batch_op.drop_column('unix_timestamp_in_ms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heartrate_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unix_timestamp_in_ms', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_index('ix_heartrate_user_id_time')
        batch_op.create_index('ix_heartrate_user_id_time', ['user_id', 'unix_timestamp_in_ms'], unique=False)
        batch_op.drop_column('unix_timestamp')

    with op.batch_alter_table('acceleration_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unix_timestamp_in_ms', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_index('ix_acceleration_user_id_time')
        batch_op.create_index('ix_acceleration_user_id_time', ['user_id', 'unix_timestamp_in_ms'], unique=False)
        batch_op.drop_column('unix_timestamp')

    # ### end Alembic commands ###
