"""Add participant counter and signed informed consent

Revision ID: 5296a33c57a9
Revises: bc14ac39e5fb
Create Date: 2024-12-12 21:33:25.840412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5296a33c57a9'
down_revision = 'bc14ac39e5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_counter', sa.Integer(), nullable=True))

    with op.batch_alter_table('studies_x_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signed_informed_consent', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studies_x_users', schema=None) as batch_op:
        batch_op.drop_column('signed_informed_consent')

    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.drop_column('participant_counter')

    # ### end Alembic commands ###
