"""add acceleration and heartrate tables

Revision ID: 6cf3212f283f
Revises: aeaf78f5e9db
Create Date: 2024-12-15 00:31:27.813041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf3212f283f'
down_revision = 'aeaf78f5e9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acceleration_metrics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('acceleration_x', sa.Integer(), nullable=True),
    sa.Column('acceleration_y', sa.Integer(), nullable=True),
    sa.Column('acceleration_z', sa.Integer(), nullable=True),
    sa.Column('vector_magnitude', sa.Float(), nullable=True),
    sa.Column('effective_time_frame', sa.String(), nullable=True),
    sa.Column('sensor_body_location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'time')
    )
    with op.batch_alter_table('acceleration_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_acceleration_user_id_time', ['user_id', 'time'], unique=False)

    op.create_table('heartrate_metrics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('heartrate', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'time')
    )
    with op.batch_alter_table('heartrate_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_heartrate_user_id_time', ['user_id', 'time'], unique=False)

    op.create_table('studies_x_principal_investigators',
    sa.Column('principal_investigator_id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['principal_investigator_id'], ['principal_investigators.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('principal_investigator_id', 'study_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studies_x_principal_investigators')
    with op.batch_alter_table('heartrate_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_heartrate_user_id_time')

    op.drop_table('heartrate_metrics')
    with op.batch_alter_table('acceleration_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_acceleration_user_id_time')

    op.drop_table('acceleration_metrics')
    # ### end Alembic commands ###
