"""Change datetime to unix_timestamp_in_ms for accel and heartrate tables

Revision ID: 70d590c4b8d5
Revises: 6cf3212f283f
Create Date: 2024-12-16 10:22:33.849362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70d590c4b8d5'
down_revision = '6cf3212f283f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acceleration_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unix_timestamp_in_ms', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_acceleration_user_id_time')
        batch_op.create_index('ix_acceleration_user_id_time', ['user_id', 'unix_timestamp_in_ms'], unique=False)
        batch_op.drop_column('time')

    with op.batch_alter_table('heartrate_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unix_timestamp_in_ms', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_heartrate_user_id_time')
        batch_op.create_index('ix_heartrate_user_id_time', ['user_id', 'unix_timestamp_in_ms'], unique=False)
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heartrate_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_index('ix_heartrate_user_id_time')
        batch_op.create_index('ix_heartrate_user_id_time', ['user_id', 'time'], unique=False)
        batch_op.drop_column('unix_timestamp_in_ms')

    with op.batch_alter_table('acceleration_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_index('ix_acceleration_user_id_time')
        batch_op.create_index('ix_acceleration_user_id_time', ['user_id', 'time'], unique=False)
        batch_op.drop_column('unix_timestamp_in_ms')

    # ### end Alembic commands ###
