"""delete unnecesary metric fields

Revision ID: a5965afb3323
Revises: cab01b0839d3
Create Date: 2024-12-16 12:25:39.686629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5965afb3323'
down_revision = 'cab01b0839d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acceleration_metrics', schema=None) as batch_op:
        batch_op.drop_column('effective_time_frame')
        batch_op.drop_column('sensor_body_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acceleration_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensor_body_location', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('effective_time_frame', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
