"""Update duration column name

Revision ID: bc14ac39e5fb
Revises: ff5922fed3dd
Create Date: 2024-12-12 15:59:04.142600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc14ac39e5fb'
down_revision = 'ff5922fed3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))
        batch_op.drop_column('duration_in_sec')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_in_sec', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
