"""Change unix timestamp integer to biginteger for metrics tables

Revision ID: cab01b0839d3
Revises: 70d590c4b8d5
Create Date: 2024-12-16 10:30:50.019386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab01b0839d3'
down_revision = '70d590c4b8d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acceleration_metrics', schema=None) as batch_op:
        batch_op.alter_column('unix_timestamp_in_ms',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('heartrate_metrics', schema=None) as batch_op:
        batch_op.alter_column('unix_timestamp_in_ms',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heartrate_metrics', schema=None) as batch_op:
        batch_op.alter_column('unix_timestamp_in_ms',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('acceleration_metrics', schema=None) as batch_op:
        batch_op.alter_column('unix_timestamp_in_ms',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
