"""Create study, metrics and intermediate relationship tables v1

Revision ID: ff5922fed3dd
Revises: 75fbed04ce7a
Create Date: 2024-12-12 15:48:07.273499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5922fed3dd'
down_revision = '75fbed04ce7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('duration_in_sec', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('inclusion_criteria', sa.Text(), nullable=False),
    sa.Column('informed_consent', sa.Text(), nullable=False),
    sa.Column('num_participants', sa.Integer(), nullable=True),
    sa.Column('principal_investigator_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['principal_investigator_id'], ['principal_investigators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('studies_x_metrics',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('study_id', 'metric_id')
    )
    op.create_table('studies_x_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('participant_num', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'study_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studies_x_users')
    op.drop_table('studies_x_metrics')
    op.drop_table('studies')
    op.drop_table('metrics')
    # ### end Alembic commands ###
